name: calling resuable workflow
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [main]
jobs:
  calling-reuse-workflow-tar:
    if: ${{github.event}} == 'push'
    uses: ./.github/workflows/tar.yml
    with:
      tarfilename: "${{ secrets.TAR_NAME }}" 
  
  calling-reuse-workflow-zip:
    if: ${{github.event == 'pull_request'}}
    uses: ./.github/workflows/zip.yml
    with:
      vname: vijay
