name: calling resuable workflow
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [main]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout
     uses: actions/checkout@v2
   - name: push changes to remote
     run: |
      git config --global user.name ${{ secrets.USER_NAME }} 
      git config --global user.email ${{ secrets.USER_EMAIL }}
      git remote set-url origin https://rajkumarvijay:${{ secrets.TOKEN }}@github.com/rajkumarvijay/reusable-.git
      git pull 
      git add .
      git commit -m "commiting from other repo"
      git push -u origin main
  #calling-reuse-workflow-tar:
   # if: ${{github.event}} == 'push'
    #uses: ./.github/workflows/tar.yml
    #with:
     # tarfilename: ${{ secrets.TAR_NAME }}
  
  #calling-reuse-workflow-zip:
   # if: ${{github.event == 'pull_request'}}
    #uses: ./.github/workflows/zip.yml
    #with:
     # vname: vijay
